//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ESolutions.LifeLog.Models", "FK_ActionLogs_Actions", "Actions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ESolutions.LifeLog.Models.Action), "ActionLogs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ESolutions.LifeLog.Models.ActionLog), true)]
[assembly: EdmRelationshipAttribute("ESolutions.LifeLog.Models", "FK_ActionLogs_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ESolutions.LifeLog.Models.User), "ActionLogs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ESolutions.LifeLog.Models.ActionLog), true)]
[assembly: EdmRelationshipAttribute("ESolutions.LifeLog.Models", "FK_BloodPressures_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ESolutions.LifeLog.Models.User), "BloodPressures", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ESolutions.LifeLog.Models.BloodPressure), true)]
[assembly: EdmRelationshipAttribute("ESolutions.LifeLog.Models", "FK_BodyMeasures_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ESolutions.LifeLog.Models.User), "BodyMeasures", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ESolutions.LifeLog.Models.BodyMeasure), true)]
[assembly: EdmRelationshipAttribute("ESolutions.LifeLog.Models", "FK_Ingestions_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ESolutions.LifeLog.Models.User), "Ingestions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ESolutions.LifeLog.Models.Ingestion), true)]
[assembly: EdmRelationshipAttribute("ESolutions.LifeLog.Models", "FK_SuccessLogs_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ESolutions.LifeLog.Models.User), "SuccessLogs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ESolutions.LifeLog.Models.SuccessLog), true)]

#endregion

namespace ESolutions.LifeLog.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyDataContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyDataContext object using the connection string found in the 'MyDataContext' section of the application configuration file.
        /// </summary>
        public MyDataContext() : base("name=MyDataContext", "MyDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDataContext object.
        /// </summary>
        public MyDataContext(string connectionString) : base(connectionString, "MyDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyDataContext object.
        /// </summary>
        public MyDataContext(EntityConnection connection) : base(connection, "MyDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ActionLog> ActionLogs
        {
            get
            {
                if ((_ActionLogs == null))
                {
                    _ActionLogs = base.CreateObjectSet<ActionLog>("ActionLogs");
                }
                return _ActionLogs;
            }
        }
        private ObjectSet<ActionLog> _ActionLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Action> Actions
        {
            get
            {
                if ((_Actions == null))
                {
                    _Actions = base.CreateObjectSet<Action>("Actions");
                }
                return _Actions;
            }
        }
        private ObjectSet<Action> _Actions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BloodPressure> BloodPressures
        {
            get
            {
                if ((_BloodPressures == null))
                {
                    _BloodPressures = base.CreateObjectSet<BloodPressure>("BloodPressures");
                }
                return _BloodPressures;
            }
        }
        private ObjectSet<BloodPressure> _BloodPressures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BodyMeasure> BodyMeasures
        {
            get
            {
                if ((_BodyMeasures == null))
                {
                    _BodyMeasures = base.CreateObjectSet<BodyMeasure>("BodyMeasures");
                }
                return _BodyMeasures;
            }
        }
        private ObjectSet<BodyMeasure> _BodyMeasures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingestion> Ingestions
        {
            get
            {
                if ((_Ingestions == null))
                {
                    _Ingestions = base.CreateObjectSet<Ingestion>("Ingestions");
                }
                return _Ingestions;
            }
        }
        private ObjectSet<Ingestion> _Ingestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhysicalActivityLevel> PhysicalActivityLevels
        {
            get
            {
                if ((_PhysicalActivityLevels == null))
                {
                    _PhysicalActivityLevels = base.CreateObjectSet<PhysicalActivityLevel>("PhysicalActivityLevels");
                }
                return _PhysicalActivityLevels;
            }
        }
        private ObjectSet<PhysicalActivityLevel> _PhysicalActivityLevels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SuccessLog> SuccessLogs
        {
            get
            {
                if ((_SuccessLogs == null))
                {
                    _SuccessLogs = base.CreateObjectSet<SuccessLog>("SuccessLogs");
                }
                return _SuccessLogs;
            }
        }
        private ObjectSet<SuccessLog> _SuccessLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ActionLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActionLogs(ActionLog actionLog)
        {
            base.AddObject("ActionLogs", actionLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Actions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActions(Action action)
        {
            base.AddObject("Actions", action);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BloodPressures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBloodPressures(BloodPressure bloodPressure)
        {
            base.AddObject("BloodPressures", bloodPressure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BodyMeasures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBodyMeasures(BodyMeasure bodyMeasure)
        {
            base.AddObject("BodyMeasures", bodyMeasure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngestions(Ingestion ingestion)
        {
            base.AddObject("Ingestions", ingestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhysicalActivityLevels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhysicalActivityLevels(PhysicalActivityLevel physicalActivityLevel)
        {
            base.AddObject("PhysicalActivityLevels", physicalActivityLevel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SuccessLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSuccessLogs(SuccessLog successLog)
        {
            base.AddObject("SuccessLogs", successLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="Action")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Action : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Action object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="consumption">Initial value of the Consumption property.</param>
        public static Action CreateAction(global::System.Guid guid, global::System.String name, global::System.Double consumption)
        {
            Action action = new Action();
            action.Guid = guid;
            action.Name = name;
            action.Consumption = consumption;
            return action;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Consumption
        {
            get
            {
                return _Consumption;
            }
            set
            {
                OnConsumptionChanging(value);
                ReportPropertyChanging("Consumption");
                _Consumption = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Consumption");
                OnConsumptionChanged();
            }
        }
        private global::System.Double _Consumption;
        partial void OnConsumptionChanging(global::System.Double value);
        partial void OnConsumptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_ActionLogs_Actions", "ActionLogs")]
        public EntityCollection<ActionLog> ActionLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ActionLog>("ESolutions.LifeLog.Models.FK_ActionLogs_Actions", "ActionLogs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ActionLog>("ESolutions.LifeLog.Models.FK_ActionLogs_Actions", "ActionLogs", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="ActionLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActionLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ActionLog object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="userGuid">Initial value of the UserGuid property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="actionGuid">Initial value of the ActionGuid property.</param>
        /// <param name="durationInMinutes">Initial value of the DurationInMinutes property.</param>
        public static ActionLog CreateActionLog(global::System.Guid guid, global::System.Guid userGuid, global::System.DateTime date, global::System.Guid actionGuid, global::System.Int32 durationInMinutes)
        {
            ActionLog actionLog = new ActionLog();
            actionLog.Guid = guid;
            actionLog.UserGuid = userGuid;
            actionLog.Date = date;
            actionLog.ActionGuid = actionGuid;
            actionLog.DurationInMinutes = durationInMinutes;
            return actionLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserGuid
        {
            get
            {
                return _UserGuid;
            }
            set
            {
                OnUserGuidChanging(value);
                ReportPropertyChanging("UserGuid");
                _UserGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserGuid");
                OnUserGuidChanged();
            }
        }
        private global::System.Guid _UserGuid;
        partial void OnUserGuidChanging(global::System.Guid value);
        partial void OnUserGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ActionGuid
        {
            get
            {
                return _ActionGuid;
            }
            set
            {
                OnActionGuidChanging(value);
                ReportPropertyChanging("ActionGuid");
                _ActionGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionGuid");
                OnActionGuidChanged();
            }
        }
        private global::System.Guid _ActionGuid;
        partial void OnActionGuidChanging(global::System.Guid value);
        partial void OnActionGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DurationInMinutes
        {
            get
            {
                return _DurationInMinutes;
            }
            set
            {
                OnDurationInMinutesChanging(value);
                ReportPropertyChanging("DurationInMinutes");
                _DurationInMinutes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DurationInMinutes");
                OnDurationInMinutesChanged();
            }
        }
        private global::System.Int32 _DurationInMinutes;
        partial void OnDurationInMinutesChanging(global::System.Int32 value);
        partial void OnDurationInMinutesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_ActionLogs_Actions", "Actions")]
        public Action Action
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Action>("ESolutions.LifeLog.Models.FK_ActionLogs_Actions", "Actions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Action>("ESolutions.LifeLog.Models.FK_ActionLogs_Actions", "Actions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Action> ActionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Action>("ESolutions.LifeLog.Models.FK_ActionLogs_Actions", "Actions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Action>("ESolutions.LifeLog.Models.FK_ActionLogs_Actions", "Actions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_ActionLogs_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_ActionLogs_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_ActionLogs_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_ActionLogs_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ESolutions.LifeLog.Models.FK_ActionLogs_Users", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="BloodPressure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BloodPressure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BloodPressure object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="userGuid">Initial value of the UserGuid property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="heartRate">Initial value of the HeartRate property.</param>
        /// <param name="systolic">Initial value of the Systolic property.</param>
        /// <param name="diastolic">Initial value of the Diastolic property.</param>
        public static BloodPressure CreateBloodPressure(global::System.Guid guid, global::System.Guid userGuid, global::System.DateTime date, global::System.Int32 heartRate, global::System.Int32 systolic, global::System.Int32 diastolic)
        {
            BloodPressure bloodPressure = new BloodPressure();
            bloodPressure.Guid = guid;
            bloodPressure.UserGuid = userGuid;
            bloodPressure.Date = date;
            bloodPressure.HeartRate = heartRate;
            bloodPressure.Systolic = systolic;
            bloodPressure.Diastolic = diastolic;
            return bloodPressure;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserGuid
        {
            get
            {
                return _UserGuid;
            }
            set
            {
                OnUserGuidChanging(value);
                ReportPropertyChanging("UserGuid");
                _UserGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserGuid");
                OnUserGuidChanged();
            }
        }
        private global::System.Guid _UserGuid;
        partial void OnUserGuidChanging(global::System.Guid value);
        partial void OnUserGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeartRate
        {
            get
            {
                return _HeartRate;
            }
            set
            {
                OnHeartRateChanging(value);
                ReportPropertyChanging("HeartRate");
                _HeartRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeartRate");
                OnHeartRateChanged();
            }
        }
        private global::System.Int32 _HeartRate;
        partial void OnHeartRateChanging(global::System.Int32 value);
        partial void OnHeartRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Systolic
        {
            get
            {
                return _Systolic;
            }
            set
            {
                OnSystolicChanging(value);
                ReportPropertyChanging("Systolic");
                _Systolic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Systolic");
                OnSystolicChanged();
            }
        }
        private global::System.Int32 _Systolic;
        partial void OnSystolicChanging(global::System.Int32 value);
        partial void OnSystolicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Diastolic
        {
            get
            {
                return _Diastolic;
            }
            set
            {
                OnDiastolicChanging(value);
                ReportPropertyChanging("Diastolic");
                _Diastolic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diastolic");
                OnDiastolicChanged();
            }
        }
        private global::System.Int32 _Diastolic;
        partial void OnDiastolicChanging(global::System.Int32 value);
        partial void OnDiastolicChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_BloodPressures_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_BloodPressures_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_BloodPressures_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_BloodPressures_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ESolutions.LifeLog.Models.FK_BloodPressures_Users", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="BodyMeasure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BodyMeasure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BodyMeasure object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="userGuid">Initial value of the UserGuid property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="fatPercentage">Initial value of the FatPercentage property.</param>
        /// <param name="waterPercentage">Initial value of the WaterPercentage property.</param>
        /// <param name="chestMeasurement">Initial value of the ChestMeasurement property.</param>
        /// <param name="abdominalMeasurement">Initial value of the AbdominalMeasurement property.</param>
        /// <param name="hipMeasurement">Initial value of the HipMeasurement property.</param>
        /// <param name="physicalActivityLevel">Initial value of the PhysicalActivityLevel property.</param>
        /// <param name="heightInCentimeters">Initial value of the HeightInCentimeters property.</param>
        /// <param name="leftUpperArm">Initial value of the LeftUpperArm property.</param>
        /// <param name="rightUpperArm">Initial value of the RightUpperArm property.</param>
        /// <param name="leftUpperLeg">Initial value of the LeftUpperLeg property.</param>
        /// <param name="rightUpperLeg">Initial value of the RightUpperLeg property.</param>
        public static BodyMeasure CreateBodyMeasure(global::System.Guid guid, global::System.Guid userGuid, global::System.DateTime date, global::System.Double weight, global::System.Double fatPercentage, global::System.Double waterPercentage, global::System.Double chestMeasurement, global::System.Double abdominalMeasurement, global::System.Double hipMeasurement, global::System.Double physicalActivityLevel, global::System.Int32 heightInCentimeters, global::System.Double leftUpperArm, global::System.Double rightUpperArm, global::System.Double leftUpperLeg, global::System.Double rightUpperLeg)
        {
            BodyMeasure bodyMeasure = new BodyMeasure();
            bodyMeasure.Guid = guid;
            bodyMeasure.UserGuid = userGuid;
            bodyMeasure.Date = date;
            bodyMeasure.Weight = weight;
            bodyMeasure.FatPercentage = fatPercentage;
            bodyMeasure.WaterPercentage = waterPercentage;
            bodyMeasure.ChestMeasurement = chestMeasurement;
            bodyMeasure.AbdominalMeasurement = abdominalMeasurement;
            bodyMeasure.HipMeasurement = hipMeasurement;
            bodyMeasure.PhysicalActivityLevel = physicalActivityLevel;
            bodyMeasure.HeightInCentimeters = heightInCentimeters;
            bodyMeasure.LeftUpperArm = leftUpperArm;
            bodyMeasure.RightUpperArm = rightUpperArm;
            bodyMeasure.LeftUpperLeg = leftUpperLeg;
            bodyMeasure.RightUpperLeg = rightUpperLeg;
            return bodyMeasure;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserGuid
        {
            get
            {
                return _UserGuid;
            }
            set
            {
                OnUserGuidChanging(value);
                ReportPropertyChanging("UserGuid");
                _UserGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserGuid");
                OnUserGuidChanged();
            }
        }
        private global::System.Guid _UserGuid;
        partial void OnUserGuidChanging(global::System.Guid value);
        partial void OnUserGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Double _Weight;
        partial void OnWeightChanging(global::System.Double value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double FatPercentage
        {
            get
            {
                return _FatPercentage;
            }
            set
            {
                OnFatPercentageChanging(value);
                ReportPropertyChanging("FatPercentage");
                _FatPercentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FatPercentage");
                OnFatPercentageChanged();
            }
        }
        private global::System.Double _FatPercentage;
        partial void OnFatPercentageChanging(global::System.Double value);
        partial void OnFatPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double WaterPercentage
        {
            get
            {
                return _WaterPercentage;
            }
            set
            {
                OnWaterPercentageChanging(value);
                ReportPropertyChanging("WaterPercentage");
                _WaterPercentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WaterPercentage");
                OnWaterPercentageChanged();
            }
        }
        private global::System.Double _WaterPercentage;
        partial void OnWaterPercentageChanging(global::System.Double value);
        partial void OnWaterPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ChestMeasurement
        {
            get
            {
                return _ChestMeasurement;
            }
            set
            {
                OnChestMeasurementChanging(value);
                ReportPropertyChanging("ChestMeasurement");
                _ChestMeasurement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChestMeasurement");
                OnChestMeasurementChanged();
            }
        }
        private global::System.Double _ChestMeasurement;
        partial void OnChestMeasurementChanging(global::System.Double value);
        partial void OnChestMeasurementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double AbdominalMeasurement
        {
            get
            {
                return _AbdominalMeasurement;
            }
            set
            {
                OnAbdominalMeasurementChanging(value);
                ReportPropertyChanging("AbdominalMeasurement");
                _AbdominalMeasurement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AbdominalMeasurement");
                OnAbdominalMeasurementChanged();
            }
        }
        private global::System.Double _AbdominalMeasurement;
        partial void OnAbdominalMeasurementChanging(global::System.Double value);
        partial void OnAbdominalMeasurementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double HipMeasurement
        {
            get
            {
                return _HipMeasurement;
            }
            set
            {
                OnHipMeasurementChanging(value);
                ReportPropertyChanging("HipMeasurement");
                _HipMeasurement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HipMeasurement");
                OnHipMeasurementChanged();
            }
        }
        private global::System.Double _HipMeasurement;
        partial void OnHipMeasurementChanging(global::System.Double value);
        partial void OnHipMeasurementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double PhysicalActivityLevel
        {
            get
            {
                return _PhysicalActivityLevel;
            }
            set
            {
                OnPhysicalActivityLevelChanging(value);
                ReportPropertyChanging("PhysicalActivityLevel");
                _PhysicalActivityLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhysicalActivityLevel");
                OnPhysicalActivityLevelChanged();
            }
        }
        private global::System.Double _PhysicalActivityLevel;
        partial void OnPhysicalActivityLevelChanging(global::System.Double value);
        partial void OnPhysicalActivityLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeightInCentimeters
        {
            get
            {
                return _HeightInCentimeters;
            }
            set
            {
                OnHeightInCentimetersChanging(value);
                ReportPropertyChanging("HeightInCentimeters");
                _HeightInCentimeters = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeightInCentimeters");
                OnHeightInCentimetersChanged();
            }
        }
        private global::System.Int32 _HeightInCentimeters;
        partial void OnHeightInCentimetersChanging(global::System.Int32 value);
        partial void OnHeightInCentimetersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double LeftUpperArm
        {
            get
            {
                return _LeftUpperArm;
            }
            set
            {
                OnLeftUpperArmChanging(value);
                ReportPropertyChanging("LeftUpperArm");
                _LeftUpperArm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LeftUpperArm");
                OnLeftUpperArmChanged();
            }
        }
        private global::System.Double _LeftUpperArm;
        partial void OnLeftUpperArmChanging(global::System.Double value);
        partial void OnLeftUpperArmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double RightUpperArm
        {
            get
            {
                return _RightUpperArm;
            }
            set
            {
                OnRightUpperArmChanging(value);
                ReportPropertyChanging("RightUpperArm");
                _RightUpperArm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RightUpperArm");
                OnRightUpperArmChanged();
            }
        }
        private global::System.Double _RightUpperArm;
        partial void OnRightUpperArmChanging(global::System.Double value);
        partial void OnRightUpperArmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double LeftUpperLeg
        {
            get
            {
                return _LeftUpperLeg;
            }
            set
            {
                OnLeftUpperLegChanging(value);
                ReportPropertyChanging("LeftUpperLeg");
                _LeftUpperLeg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LeftUpperLeg");
                OnLeftUpperLegChanged();
            }
        }
        private global::System.Double _LeftUpperLeg;
        partial void OnLeftUpperLegChanging(global::System.Double value);
        partial void OnLeftUpperLegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double RightUpperLeg
        {
            get
            {
                return _RightUpperLeg;
            }
            set
            {
                OnRightUpperLegChanging(value);
                ReportPropertyChanging("RightUpperLeg");
                _RightUpperLeg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RightUpperLeg");
                OnRightUpperLegChanged();
            }
        }
        private global::System.Double _RightUpperLeg;
        partial void OnRightUpperLegChanging(global::System.Double value);
        partial void OnRightUpperLegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> SidePictureGuid
        {
            get
            {
                return _SidePictureGuid;
            }
            set
            {
                OnSidePictureGuidChanging(value);
                ReportPropertyChanging("SidePictureGuid");
                _SidePictureGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SidePictureGuid");
                OnSidePictureGuidChanged();
            }
        }
        private Nullable<global::System.Guid> _SidePictureGuid;
        partial void OnSidePictureGuidChanging(Nullable<global::System.Guid> value);
        partial void OnSidePictureGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> FrontPictureGuid
        {
            get
            {
                return _FrontPictureGuid;
            }
            set
            {
                OnFrontPictureGuidChanging(value);
                ReportPropertyChanging("FrontPictureGuid");
                _FrontPictureGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FrontPictureGuid");
                OnFrontPictureGuidChanged();
            }
        }
        private Nullable<global::System.Guid> _FrontPictureGuid;
        partial void OnFrontPictureGuidChanging(Nullable<global::System.Guid> value);
        partial void OnFrontPictureGuidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_BodyMeasures_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_BodyMeasures_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_BodyMeasures_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_BodyMeasures_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ESolutions.LifeLog.Models.FK_BodyMeasures_Users", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="Ingestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingestion object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="userGuid">Initial value of the UserGuid property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="pictureGuid">Initial value of the PictureGuid property.</param>
        public static Ingestion CreateIngestion(global::System.Guid guid, global::System.Guid userGuid, global::System.DateTime date, global::System.Guid pictureGuid)
        {
            Ingestion ingestion = new Ingestion();
            ingestion.Guid = guid;
            ingestion.UserGuid = userGuid;
            ingestion.Date = date;
            ingestion.PictureGuid = pictureGuid;
            return ingestion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserGuid
        {
            get
            {
                return _UserGuid;
            }
            set
            {
                OnUserGuidChanging(value);
                ReportPropertyChanging("UserGuid");
                _UserGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserGuid");
                OnUserGuidChanged();
            }
        }
        private global::System.Guid _UserGuid;
        partial void OnUserGuidChanging(global::System.Guid value);
        partial void OnUserGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PictureGuid
        {
            get
            {
                return _PictureGuid;
            }
            set
            {
                OnPictureGuidChanging(value);
                ReportPropertyChanging("PictureGuid");
                _PictureGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PictureGuid");
                OnPictureGuidChanged();
            }
        }
        private global::System.Guid _PictureGuid;
        partial void OnPictureGuidChanging(global::System.Guid value);
        partial void OnPictureGuidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_Ingestions_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_Ingestions_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_Ingestions_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_Ingestions_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ESolutions.LifeLog.Models.FK_Ingestions_Users", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="PhysicalActivityLevel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhysicalActivityLevel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhysicalActivityLevel object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="factor">Initial value of the Factor property.</param>
        public static PhysicalActivityLevel CreatePhysicalActivityLevel(global::System.Guid guid, global::System.String name, global::System.Double factor)
        {
            PhysicalActivityLevel physicalActivityLevel = new PhysicalActivityLevel();
            physicalActivityLevel.Guid = guid;
            physicalActivityLevel.Name = name;
            physicalActivityLevel.Factor = factor;
            return physicalActivityLevel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Factor
        {
            get
            {
                return _Factor;
            }
            set
            {
                OnFactorChanging(value);
                ReportPropertyChanging("Factor");
                _Factor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Factor");
                OnFactorChanged();
            }
        }
        private global::System.Double _Factor;
        partial void OnFactorChanging(global::System.Double value);
        partial void OnFactorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="SuccessLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SuccessLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SuccessLog object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="userGuid">Initial value of the UserGuid property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static SuccessLog CreateSuccessLog(global::System.Guid guid, global::System.Guid userGuid, global::System.DateTime date, global::System.String text)
        {
            SuccessLog successLog = new SuccessLog();
            successLog.Guid = guid;
            successLog.UserGuid = userGuid;
            successLog.Date = date;
            successLog.Text = text;
            return successLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserGuid
        {
            get
            {
                return _UserGuid;
            }
            set
            {
                OnUserGuidChanging(value);
                ReportPropertyChanging("UserGuid");
                _UserGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserGuid");
                OnUserGuidChanged();
            }
        }
        private global::System.Guid _UserGuid;
        partial void OnUserGuidChanging(global::System.Guid value);
        partial void OnUserGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Int32 _type;
        partial void OntypeChanging(global::System.Int32 value);
        partial void OntypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_SuccessLogs_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_SuccessLogs_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_SuccessLogs_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ESolutions.LifeLog.Models.FK_SuccessLogs_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ESolutions.LifeLog.Models.FK_SuccessLogs_Users", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ESolutions.LifeLog.Models", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="hash">Initial value of the Hash property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="heightInCentimeters">Initial value of the HeightInCentimeters property.</param>
        public static User CreateUser(global::System.Guid guid, global::System.String email, global::System.Byte[] hash, global::System.DateTime dateOfBirth, global::System.Int32 heightInCentimeters)
        {
            User user = new User();
            user.Guid = guid;
            user.Email = email;
            user.Hash = hash;
            user.DateOfBirth = dateOfBirth;
            user.HeightInCentimeters = heightInCentimeters;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Hash
        {
            get
            {
                return StructuralObject.GetValidValue(_Hash);
            }
            set
            {
                OnHashChanging(value);
                ReportPropertyChanging("Hash");
                _Hash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Hash");
                OnHashChanged();
            }
        }
        private global::System.Byte[] _Hash;
        partial void OnHashChanging(global::System.Byte[] value);
        partial void OnHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeightInCentimeters
        {
            get
            {
                return _HeightInCentimeters;
            }
            set
            {
                OnHeightInCentimetersChanging(value);
                ReportPropertyChanging("HeightInCentimeters");
                _HeightInCentimeters = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeightInCentimeters");
                OnHeightInCentimetersChanged();
            }
        }
        private global::System.Int32 _HeightInCentimeters;
        partial void OnHeightInCentimetersChanging(global::System.Int32 value);
        partial void OnHeightInCentimetersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.Int32 _gender;
        partial void OngenderChanging(global::System.Int32 value);
        partial void OngenderChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_ActionLogs_Users", "ActionLogs")]
        public EntityCollection<ActionLog> ActionLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ActionLog>("ESolutions.LifeLog.Models.FK_ActionLogs_Users", "ActionLogs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ActionLog>("ESolutions.LifeLog.Models.FK_ActionLogs_Users", "ActionLogs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_BloodPressures_Users", "BloodPressures")]
        public EntityCollection<BloodPressure> BloodPressures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BloodPressure>("ESolutions.LifeLog.Models.FK_BloodPressures_Users", "BloodPressures");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BloodPressure>("ESolutions.LifeLog.Models.FK_BloodPressures_Users", "BloodPressures", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_BodyMeasures_Users", "BodyMeasures")]
        public EntityCollection<BodyMeasure> BodyMeasures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BodyMeasure>("ESolutions.LifeLog.Models.FK_BodyMeasures_Users", "BodyMeasures");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BodyMeasure>("ESolutions.LifeLog.Models.FK_BodyMeasures_Users", "BodyMeasures", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_Ingestions_Users", "Ingestions")]
        public EntityCollection<Ingestion> Ingestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingestion>("ESolutions.LifeLog.Models.FK_Ingestions_Users", "Ingestions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingestion>("ESolutions.LifeLog.Models.FK_Ingestions_Users", "Ingestions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ESolutions.LifeLog.Models", "FK_SuccessLogs_Users", "SuccessLogs")]
        public EntityCollection<SuccessLog> SuccessLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SuccessLog>("ESolutions.LifeLog.Models.FK_SuccessLogs_Users", "SuccessLogs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SuccessLog>("ESolutions.LifeLog.Models.FK_SuccessLogs_Users", "SuccessLogs", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
